spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #是否从eureka server中获取注册信息，默认是true
    #若单节点得eureka server,不需要同步其他节点的数据， 设置为false
    fetch-registry: false
    #是否将自己注册到Eureka server，由于单节点的es false!
    register-with-eureka: false
    #设置eureka server所在的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/